
name: Auto RDF triple generation
run-name: |- 
  Auto RDF triple generation.

on:
  issues:
    types: [reopened, opened, closed]



jobs:
  Generate-Triples:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Generation
        run: |
          pip install rdflib
          python scripy.py
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Hallo, die RDF-Daten wurden erfolgreich generiert!"}' ${{ secrets.WEBHOOK }}
