
name: Auto RDF triple generation
run-name: |- 
  Auto RDF triple generation.

on: workflow_dispatch


jobs:
  Generate-Triples:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          repository: FlorianRupp/kim-workshop-23-cicd
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Generator Bot"
      - name: Setup Python
        run: |
          pip install rdflib
      - name: Generation
        run: |
          cd data
          python script.py
      - name: Save data
        uses: actions/upload-artifact@v3
        with:
          name: Generated Movies RDF Data (ttl)
          path: data/movies.ttl
      - name: Notify Discord
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Hallo, die RDF-Daten wurden erfolgreich generiert!"}' ${{ secrets.WEBHOOK }}
