
name: Auto RDF triple generation
run-name: |- 
  Auto RDF triple generation.

on:
  issues:
    types: [reopened, opened, closed]



jobs:
  Generate-Triples:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
        with:
          repository: FlorianRupp/kim-workshop-23-cicd
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Generator Bot"
      - name: Generation
        run: |
          pip install rdflib
          python script.py
      - name: Archive data
        id: archive-data
        uses: actions/upload-artifact@v3
        with:
          name: Generated Movies RDF Data (ttl)
          path: movies.ttl
      - name: Notify Discord
        run: |
          echo "The artifact ID is ${{ steps.archive-data.outputs.upload_url }}"
          echo "The artifact ID is ${{ steps.archive-data.outputs.asset_id }}"
          artifact=${{ steps.archive-data.outputs.upload_url }}
          echo $artifact
          curl -H "Content-Type: application/json" -X POST -d '{"content": "Hallo, die RDF-Daten wurden erfolgreich generiert! $artifact "}' ${{ secrets.WEBHOOK }}
